# Generated by Django 3.0.1 on 2020-07-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'ARTIST',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_customed', models.NullBooleanField()),
                ('custom_option', models.TextField(max_length=3000, null=True)),
                ('introduction', models.TextField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ARTIST', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artist')),
            ],
            options={
                'db_table': 'ARTWORK',
            },
        ),
        migrations.CreateModel(
            name='ArtworkColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=2500, null=True)),
            ],
            options={
                'db_table': 'ARTWORK_COLOR',
            },
        ),
        migrations.CreateModel(
            name='ArtworkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500, null=True)),
            ],
            options={
                'db_table': 'ARTWORK_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DEVICE',
            },
        ),
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'DEVICE_BRAND',
            },
        ),
        migrations.CreateModel(
            name='DeviceColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device')),
            ],
            options={
                'db_table': 'DEVICE_COLOR',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'ITEM',
            },
        ),
        migrations.CreateModel(
            name='RegularArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.URLField(max_length=2500, null=True)),
                ('image_2', models.URLField(max_length=2500, null=True)),
                ('image_3', models.URLField(max_length=2500, null=True)),
                ('image_4', models.URLField(max_length=2500, null=True)),
                ('image_5', models.URLField(max_length=2500, null=True)),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('ARTWORK_COLOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkColor')),
                ('DEVICE_COLOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.DeviceColor')),
            ],
            options={
                'db_table': 'REGULAR_ARTWORK_IMAGE',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.DeviceBrand'),
        ),
        migrations.CreateModel(
            name='CustomArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.URLField(max_length=2500, null=True)),
                ('image_2', models.URLField(max_length=2500, null=True)),
                ('image_3', models.URLField(max_length=2500, null=True)),
                ('image_4', models.URLField(max_length=2500, null=True)),
                ('image_5', models.URLField(max_length=2500, null=True)),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('ARTWORK_COLOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkColor')),
            ],
            options={
                'db_table': 'CUSTOM_ARTWORK_IMAGE',
            },
        ),
        migrations.CreateModel(
            name='ArtworkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(null=True)),
                ('comment_title', models.CharField(max_length=500, null=True)),
                ('comment_text', models.TextField(max_length=1000, null=True)),
                ('is_buyer', models.NullBooleanField()),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'ARTWORK_REVIEW',
            },
        ),
        migrations.CreateModel(
            name='ArtworkPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('DEVICE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device')),
            ],
            options={
                'db_table': 'ARTWORK_PRICE',
            },
        ),
        migrations.CreateModel(
            name='ArtworkColorArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARTWORK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('ARTWORK_COLOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkColor')),
                ('DEVICE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device')),
            ],
            options={
                'db_table': 'ARTWORK_COLOR_ARTWORK',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='ARTWORK_TYPE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkType'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='DEVICE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='ITME',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Item'),
        ),
    ]
