# Generated by Django 3.0.1 on 2020-01-16 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_customed', models.NullBooleanField()),
                ('custom_option', models.TextField(max_length=3000, null=True)),
                ('introduction', models.TextField(max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artist')),
            ],
            options={
                'db_table': 'artworks',
            },
        ),
        migrations.CreateModel(
            name='ArtworkColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=2500, null=True)),
            ],
            options={
                'db_table': 'artwork_colors',
            },
        ),
        migrations.CreateModel(
            name='ArtworkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500, null=True)),
            ],
            options={
                'db_table': 'artwork_types',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('overlay_image', models.URLField(max_length=2500)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'device_brands',
            },
        ),
        migrations.CreateModel(
            name='DeviceColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device')),
            ],
            options={
                'db_table': 'device_colors',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='RegularArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.URLField(max_length=2500, null=True)),
                ('image_2', models.URLField(max_length=2500, null=True)),
                ('image_3', models.URLField(max_length=2500, null=True)),
                ('image_4', models.URLField(max_length=2500, null=True)),
                ('image_5', models.URLField(max_length=2500, null=True)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('artwork_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkColor')),
                ('device_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.DeviceColor')),
            ],
            options={
                'db_table': 'regular_artwork_images',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.DeviceBrand'),
        ),
        migrations.CreateModel(
            name='CustomArtworkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.URLField(max_length=2500, null=True)),
                ('image_2', models.URLField(max_length=2500, null=True)),
                ('image_3', models.URLField(max_length=2500, null=True)),
                ('image_4', models.URLField(max_length=2500, null=True)),
                ('image_5', models.URLField(max_length=2500, null=True)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('artwork_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkColor')),
            ],
            options={
                'db_table': 'custom_artwork_images',
            },
        ),
        migrations.CreateModel(
            name='ArtworkReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(null=True)),
                ('comment_title', models.CharField(max_length=500, null=True)),
                ('comment_text', models.TextField(max_length=1000, null=True)),
                ('is_buyer', models.NullBooleanField()),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'artwork_reviews',
            },
        ),
        migrations.CreateModel(
            name='ArtworkPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device')),
            ],
            options={
                'db_table': 'artwork_prices',
            },
        ),
        migrations.CreateModel(
            name='ArtworkColorArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Artwork')),
                ('artwork_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkColor')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device')),
            ],
            options={
                'db_table': 'artwork_color_artworks',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.ArtworkType'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='color',
            field=models.ManyToManyField(related_name='artwork_artworkcolor', through='artwork.ArtworkColorArtwork', to='artwork.ArtworkColor'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Device'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.Item'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.ManyToManyField(related_name='artwork_price', through='artwork.ArtworkPrice', to='artwork.Device'),
        ),
    ]
