# Generated by Django 3.1 on 2020-08-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='ARTWORK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_ARTWORK', to='artwork.artwork'),
        ),
    ]
