# Generated by Django 3.1 on 2020-08-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20200822_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='ARTWORK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.artwork'),
        ),
    ]
