# Generated by Django 3.0.1 on 2020-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custom_info',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_checkout',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
